language: ruby
rvm:
  - 2.6.3
bundler_args: "--without development production --deployment"
cache:
  bundler: true
  directories:
    - node_modules
    - vendor/assets/bower_components
env:
  global:
    - "PATH=$PWD/node_modules/.bin:$PATH"
  matrix:
    - FORCE_POSTGRES=true
    - DO_NOT_FORCE_POSTGRES=true
before_install:
  - 'env'
  - 'npm install'
  - 'echo ''gem: --no-document'' > ~/.gemrc'
  - 'gem update --system'
  - 'gem install bundler'
before_script:
  - 'bundle exec rake bower:install:development'
  - "./config/before-travis.sh"
script:
  - "bundle exec rake rspec_with_retries"
  - "bundle exec rake jasmine:ci"

sudo: false
